#!/usr/bin/env python3
"""
Bundle Packager
===============
After all ebooks are generated, assembles the final deliverable:

  output/bundles/<bundle_slug>/
    ebooks/
      01_<title>.pdf
      02_<title>.pdf
      ...
    README.md       ← generated by one Gemini call (200-400 words)
    manifest.json   ← machine-readable metadata

Then ZIPs the folder to output/bundles/<bundle_slug>.zip
"""

from __future__ import annotations

import json
import os
import re
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

import google.generativeai as genai

from config import Config

PACKAGE_MODEL = "gemini-2.5-pro"


class BundlePackager:
    """Packages ebook PDFs into a final ZIP bundle with README and manifest."""

    def package(
        self,
        bundle_slug: str,
        bundle_plan: Dict,
        pdf_results: List[Dict],
        output_dir: Path,
        language: str = "English",
        verbose: bool = True,
    ) -> Dict:
        """
        Creates README.md, manifest.json, and ZIP under output/bundles/.

        Args:
            bundle_slug:  URL-safe slug for the bundle directory/zip name.
            bundle_plan:  Dict returned by BundleGenerator._plan_bundle_sync.
            pdf_results:  List of per-ebook metadata dicts from _build_one_pdf.
            output_dir:   The bundle's root directory (already created).
            verbose:      Print progress.

        Returns:
            Dict with keys: zip_path, readme_path, manifest_path.
        """
        output_dir = Path(output_dir)

        # ── manifest.json ────────────────────────────────────────────────────
        manifest = self._build_manifest(bundle_plan, pdf_results)
        manifest_path = output_dir / "manifest.json"
        manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
        if verbose:
            print(f"   📋 manifest.json written ({len(pdf_results)} ebooks)")

        # ── README.md  (1 Gemini call) ───────────────────────────────────────
        readme_text = self._generate_readme(bundle_plan, pdf_results, language)
        readme_path = output_dir / "README.md"
        readme_path.write_text(readme_text, encoding="utf-8")
        if verbose:
            print(f"   📝 README.md written ({len(readme_text.split()):,} words)")

        # ── ZIP ───────────────────────────────────────────────────────────────
        zip_dir  = Path(Config.BUNDLE_OUTPUT_DIR)
        zip_dir.mkdir(parents=True, exist_ok=True)
        zip_path = zip_dir / f"{bundle_slug}.zip"

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            for item in output_dir.rglob("*"):
                if item.is_file():
                    zf.write(item, item.relative_to(output_dir.parent))

        zip_mb = zip_path.stat().st_size / (1024 * 1024)
        if verbose:
            print(f"   🗜️  {zip_path.name} ({zip_mb:.1f} MB)")

        return {
            "zip_path"     : str(zip_path),
            "readme_path"  : str(readme_path),
            "manifest_path": str(manifest_path),
        }

    # =========================================================================
    # MANIFEST
    # =========================================================================

    def _build_manifest(self, bundle_plan: Dict, pdf_results: List[Dict]) -> Dict:
        total_words = sum(r["word_count"] for r in pdf_results)
        total_chaps = sum(r["chapters"]   for r in pdf_results)
        return {
            "bundle_name"   : bundle_plan["name"],
            "positioning"   : bundle_plan.get("positioning", ""),
            "created_at"    : datetime.now(timezone.utc).isoformat(),
            "num_ebooks"    : len(pdf_results),
            "total_words"   : total_words,
            "total_chapters": total_chaps,
            "ebooks"        : [
                {
                    "index"     : r["ebook_num"],
                    "filename"  : r["filename"],
                    "title"     : r["title"],
                    "subtitle"  : r["subtitle"],
                    "angle"     : r["angle"],
                    "word_count": r["word_count"],
                    "chapters"  : r["chapters"],
                }
                for r in sorted(pdf_results, key=lambda x: x["ebook_num"])
            ],
        }

    # =========================================================================
    # README (Gemini)
    # =========================================================================

    def _generate_readme(self, bundle_plan: Dict, pdf_results: List[Dict], language: str = "English") -> str:
        from ebook_generator import _language_block
        ebook_lines = "\n".join(
            f"  {r['ebook_num']}. **{r['title']}** — {r['subtitle']}"
            for r in sorted(pdf_results, key=lambda x: x["ebook_num"])
        )
        lang_block = _language_block(language)
        prompt = f"""Write a professional, compelling bundle README (200-400 words) in Markdown.
{lang_block}
BUNDLE: {bundle_plan['name']}
POSITIONING: {bundle_plan.get('positioning','')}

EBOOKS INCLUDED:
{ebook_lines}

The README should include:
1. A compelling one-paragraph intro (what the bundle is and who it's for)
2. A "What's Inside" section listing each ebook with 1-2 sentence description
3. A "Who This Bundle Is For" section (2-3 bullet points)
4. A short "How to Use This Bundle" section (read in order, or dip in)

Rules:
- Professional, confident tone — no hype or salesy language
- Specific about what the reader gets — not vague
- Under 400 words total
- Use clean Markdown (##, **, -)"""

        for attempt in range(3):
            try:
                model    = genai.GenerativeModel(PACKAGE_MODEL)
                response = model.generate_content(
                    prompt,
                    generation_config={"temperature": 0.4, "max_output_tokens": 2048},
                )
                return response.text.strip()
            except Exception as e:
                wait = [5, 15, 45][min(attempt, 2)]
                if attempt < 2:
                    time.sleep(wait)

        # Fallback: generate a basic README without Gemini
        return self._fallback_readme(bundle_plan, pdf_results)

    def _fallback_readme(self, bundle_plan: Dict, pdf_results: List[Dict]) -> str:
        lines = [
            f"# {bundle_plan['name']}",
            "",
            bundle_plan.get("positioning", ""),
            "",
            "## What's Inside",
            "",
        ]
        for r in sorted(pdf_results, key=lambda x: x["ebook_num"]):
            lines.append(f"- **{r['title']}** — {r['subtitle']}")
        lines += [
            "",
            f"## Details",
            "",
            f"- {len(pdf_results)} ebooks",
            f"- {sum(r['word_count'] for r in pdf_results):,} total words",
            f"- {sum(r['chapters'] for r in pdf_results)} total chapters",
            "",
            f"*Generated {datetime.now().strftime('%B %Y')}*",
        ]
        return "\n".join(lines)
